apiVersion: v1
kind: pipeline
metadata:
  name: new-pipeline
  labels:
    repo: ArikMaor/ping-server
    appPort: 3000
spec:
  triggers:
    - type: scm
      repo: ArikMaor/ping-server
      events: [push, pullrequest]
      branchRegex: '.'
  contexts: []
  variables:
    - key: PORT
      value: 3000
      encrypted: false
    - key: PAPA
      value: BLA BLA
      encrypted: true
  steps:
    test_step:
      image: alpine
      commands:
      - echo "hello world"
      - echo "plain value $PORT"
      - echo "encrypted value $PAPA"
      - echo "value from context $COOKIE"
