apiVersion: v1
# Using this example you can install helm mongodb chart and set the service type as LoadBalancer instaed default ClusterIp
# https://github.com/kubernetes/charts/blob/master/stable/mongodb/values.yaml
kind: context
owner: account
metadata:
  name: helm-mongo-secret-values
spec:
  type: secret-yaml
  data:
    # All the values will be encrypted 
    serviceType: LoadBalancer
    image: mongo
    type: 
      - "encrypted"