theme = "docdock"
baseurl = "http://cli.codefresh.io"
title = "Codefresh CLI Documentation"
publishDir = "../docs"
languageCode = "en-us"
DefaultContentLanguage = "en"


pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
editURL = "https://github.com/vjeantet/hugo-theme-docdock/edit/master/exampleSite/content/"
showVisitedLinks = true # default is false
themeStyle = "original" # "original" or "flex" # default "original"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter


[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/codefresh-io/cli"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-camera'></i> Examples"
url = "/Examples"
weight = 11

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> Codefresh Documentation"
identifier = "hugodoc"
url = "https://docs.codefresh.io"
weight = 20
